image: dremio/dremio-oss
path:
  dist: "pdfs:///tmp/pdfs"
# Check out Dremio documentation for memory and cpu requirements for
# the coordinators and the executors.
# The value of memory should be in MB. CPU is in no of cores.
coordinator:
  memory: 16384
  cpu: 8
  count: 0
  # This value should NOT be set to more than 1.
  master_count: 1
  web:
    port: 9047
  client:
    port: 31010
  volumeSize: 20Gi
  # To use custom storage class, uncomment and provide the value here.
  # Otherwise the default storage class configured for your K8S cluster is used.
  #storageClass: managed-premium
executor:
  memory: 16384
  cpu: 4
  count: 1
# If your Kubernetes cluster does not support LoadBalancer,
# comment out the line below for the helm chart to succeed.
serviceType: LoadBalancer
