image: dremio/dremio-oss
path:
  dist: "pdfs:///tmp/pdfs"
# Check out Dremio documentation for memory and cpu requirements for
# the coordinators and the executors.
# The value of memory should be in MB. CPU is in no of cores.
coordinator:
  memory: 16384
  cpu: 8
  count: 1
  master_count: 1
  web:
    port: 9047
executor:
  memory: 16384
  cpu: 4
  count: 1
# If your Kubernetes cluster does not support LoadBalancer,
# comment out the line below for the helm chart to succeed.
serviceType: LoadBalancer
